---
version: "2"
linters:
  default: "all"
  exclusions:
    presets:
      - comments
    rules:
      - linters:
        - staticcheck
        # Errors often start with a type name.
        text: "ST1005: error strings should not be capitalized"

  disable:
    - "cyclop" # trips too easily on validation-heavy funcs
    - "err113" # not designing a lib
    - "exhaustruct" # zero values are a good thing
    - "forcetypeassert" # the resulting panics are used to denote explicit programming errors
    - "funcorder"
    - "gochecknoglobals"
    - "gochecknoinits"
    - "godoclint"
    - "godox"
    - "inamedparam"
    - "mnd"
    - "musttag"
    - "nlreturn"
    - "noinlineerr"
    - "nonamedreturns"
    - "paralleltest"
    - "recvcheck"
    - "unparam"
    - "unqueryvet"
    - "varnamelen"
    - "wrapcheck"
    - "wsl"
    - "wsl_v5"

  settings:
    gosec:
      excludes:
        - G115 # never a security issue in our cases
        - G304 # no, opening files is not a security issue
